// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
        if (kIsWeb) {
            return web;
        }
        switch (defaultTargetPlatform) {
            case TargetPlatform.android:
                return android;
            case TargetPlatform.iOS:
                return ios;
            case TargetPlatform.macOS:
                return macos;
            case TargetPlatform.windows:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for windows - '
                    'you can reconfigure this by running the FlutterFire CLI again.',
                );
            case TargetPlatform.linux:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for linux - '
                    'you can reconfigure this by running the FlutterFire CLI again.',
                );
            default:
                throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                );
        }
    }

    static const FirebaseOptions web = FirebaseOptions(
        apiKey: 'AIzaSyAgvp-Vuwxs9nbIKI74TYaOOWkFzxZzSq4',
        appId: '1:275490510165:web:7e1c1f7d0ae1bb88fa8bdc',
        messagingSenderId: '275490510165',
        projectId: 'recardify-7ea11',
        authDomain: 'recardify-7ea11.firebaseapp.com',
        storageBucket: 'recardify-7ea11.appspot.com',
        measurementId: 'G-5H9FX195JT',
    );

    static const FirebaseOptions android = FirebaseOptions(
        apiKey: 'AIzaSyBGcUPmpc6v1ESL01FpqV-SWWELtnY7g6A',
        appId: '1:275490510165:android:9fd2841a91826b70fa8bdc',
        messagingSenderId: '275490510165',
        projectId: 'recardify-7ea11',
        storageBucket: 'recardify-7ea11.appspot.com',
    );

    static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyAq9opBtu74YGR-0__YJK7kjfYBz8f2mwA',
        appId: '1:275490510165:ios:100e44f7fc5c6e04fa8bdc',
        messagingSenderId: '275490510165',
        projectId: 'recardify-7ea11',
        storageBucket: 'recardify-7ea11.appspot.com',
        iosBundleId: 'hpic.recardify.recardify',
    );

    static const FirebaseOptions macos = FirebaseOptions(
        apiKey: 'AIzaSyAq9opBtu74YGR-0__YJK7kjfYBz8f2mwA',
        appId: '1:275490510165:ios:4a93430d6a26db9bfa8bdc',
        messagingSenderId: '275490510165',
        projectId: 'recardify-7ea11',
        storageBucket: 'recardify-7ea11.appspot.com',
        iosBundleId: 'hpic.recardify.recardify.RunnerTests',
    );
}
